### ISSUE TITLE
ARM image & Auto-builds in Travis-Ci 

### ISSUE THREAD

**Issue by shafr** [mhubig/docker-partkeepr#14]
Hello, have you considered connecting TravisCi to your project to generate builds when code in main branch changes  ?

Also it would be great if you can generate images for ARM architectures as well (RPI, Asus tinkerboard, etc).

**Comment by mhubig** [comment]
There is already a CI/CD Pipeline connected to this repo. See here: https://hub.docker.com/r/mhubig/partkeepr/

Building an ARM Image is a great idea. Have you got some experience on this topic?

**Comment by shafr** [comment]
When I will have time - I will try to fork your repository and create another Dockerfile with Travis Build (using something like this: https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/)

Some libraries would not work, i've tried building on my Asus Tinker Board - LDAP does not exist for ARM and somehow it dies on the configuration part, so i would need to investigate it further.

**Comment by mhubig** [comment]
Maybe this is something you need to report upstream to https://github.com/partkeepr/PartKeepr ?

**Comment by mhubig** [comment]
Just for reference:
- how to install docker on raspi: https://www.docker.com/blog/happy-pi-day-docker-raspberry-pi/
- CICD with travis: https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/
- Travis offical docu: https://docs.travis-ci.com/user/multi-cpu-architectures/

Maybe Ill give it a try ... :-)

**Comment by Luxtech** [comment]
Is there al progress with the ARM port? I am trying to build the docker image on my pi and I also run in to a LDAP error.

**Comment by romi2002** [comment]
I've been able to build the docker image on a RPI 4 by changing the following line in the `Dockerfile`.
```
&& docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
```
to:
```
&& docker-php-ext-configure ldap --with-libdir=lib/ \
```
I don't know if that breaks builds for x86/x64, but it seems to work on ARM. I also had to change the MariaDB image to a compatible ARM build, in this case `jsurf/rpi-mariadb`.

**Comment by Luxtech** [comment]
> I've been able to build the docker image on a RPI 4 by changing the following line in the `Dockerfile`.
> 
> ```
> && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ \
> ```
> 
> to:
> 
> ```
> && docker-php-ext-configure ldap --with-libdir=lib/ \
> ```
> 
> I don't know if that breaks builds for x86/x64, but it seems to work on ARM. I also had to change the MariaDB image to a compatible ARM build, in this case `jsurf/rpi-mariadb`.


I changed the line in the DockerFile, rebuild the docker image and changed the MariaDB image as you mentioned, rebuilding the image worked but when i opent the partkeepr webpage i get a an error:
```
An Exception was thrown while handling: Internal Server Error
```
The docker logs showd this:
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message,
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.3. Set the 'ServerName' directive globally to suppress this message,
[Sun Jan 03 14:51:53.469064 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.1.33 configured -- resuming normal operations,
[Sun Jan 03 14:51:53.469467 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND',
<IP> - - [03/Jan/2021:14:52:59 +0000] "GET / HTTP/1.1" 500 400 "-" <Firefox version>,
```

The logs show my connection but i only get a white page with the internal server error

Edit
Solved it, was to focused on getting the image build read over the setup page section:
```
setup page (e.g.: http://localhost:8080/setup)
```

After running trough the setup I get an error when i reach the main partkeepr page:
```
Your database schema is not up-to-date! Please re-run setup immediately!
```
When i re-run the setup it fails by the "Testing for correct PHP settings" with the error: "Invalid response from server".
