### ISSUE TITLE
Unable to install.

### ISSUE THREAD

**Issue by sbeaudoin** [mhubig/docker-partkeepr#15]
Tried to install partkeepr on IIS but had problems.  So, thinking it would be a snap, I installed ubuntu desktop v18.04.1 on an hyper-v VM.  After having installed docker, when I execute the following command as suggested on your main github page :

`docker run -d -p 80:80 --name partkeepr mhubig/partkeepr`

It gives me the folllowing error : 

`"docker run" requires at least 1 argument`.

I don't understand, I have three of thems.  I suppose he don't understand them?  Consulting the help of docker confirms the -d and -p parameters, but I can't find anything for --name.

**Comment by mhubig** [comment]
https://docs.docker.com/engine/reference/run/#container-identification

**Comment by sbeaudoin** [comment]
Ok, you proved --name exist, but this don't help to solve the problem.  It looks like your documentation is missing something.

**Comment by mhubig** [comment]
What Version of docker do you have? I'm at:
```shell
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

But generally speaking, all you need is docker and:
```
$ docker run -d -p 80:80 --name partkeepr mhubig/partkeepr
```
to get the container up and running. No extra preparation ...

**Comment by sbeaudoin** [comment]
I'm earlier than you : 18.06.1-ce, client : 1.38, **Go version : go1.10.4**, Built : Fri Oct 19 19:43:14 2018, experimantal : false.  As I told in an another bug report, it didn't like the docker run, I had to remove the name parameter and do a sudo on this command as it produced an access denied.  You can close the other one by the way.

**Comment by mhubig** [comment]
This seems to be more related to [docker](https://docs.docker.com/engine/reference/commandline/cli/) in general than to this image. Closing now. But feel free to reopen if you need further assistance ...
