### ISSUE TITLE
backup database

### ISSUE THREAD

**Issue by tggo** [mhubig/docker-partkeepr#17]
any shortcut command for backuping ?
it would be nice if you added to the instructions

**Comment by mhubig** [comment]
As far as I know the only thing you need to backup is the database. In my `docker-compose.yml` example I use the [standard mariadb docker container](https://hub.docker.com/_/mariadb/), so the backup instructions for the mariadb docker container should work here too ...

**Comment by mhubig** [comment]
Closing this now, but feel free to reopen if you need further assistance!
