### ISSUE TITLE
An Exception was thrown while handling: Internal Server Error

### ISSUE THREAD

**Issue by 9600** [mhubig/docker-partkeepr#18]
Tried the latest build and 1.4.0-5 and getting this error, both with standalone use and behind Docker nginx-proxy. Is there a known good release I should be using? Or perhaps I'm missing a step?

All I'm seeing via docker logs is messages regarding determining the FQDN:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.17. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.17. Set the 'ServerName' directive globally to suppress this message
[Tue Jan 15 19:50:41.413662 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.1.24 configured -- resuming normal operations
[Tue Jan 15 19:50:41.413702 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

**Comment by 9600** [comment]
Also tried the URI /web/setup/ and get:

An Exception was thrown while handling: Not Found

**Comment by nhendin** [comment]
I am seeing the same thing as well.

**Comment by mhubig** [comment]
> Tried the latest build and 1.4.0-5 and getting this error, both with standalone use and behind Docker nginx-proxy. Is there a known good release I should be using? Or perhaps I'm missing a step?

Have you tried (latest version is 1.4.0-15):
```shell
export PARTKEEPR_OKTOPART_APIKEY=0123456
docker run -d -p 80:80 -e PARTKEEPR_OKTOPART_APIKEY --name partkeepr mhubig/partkeepr:1.4.0-15
```
Then open http://localhost/setup/

**Comment by 9600** [comment]
Hm, that URL is working for me now. Was pretty sure I'd tried it before. Anyway, thanks for the help!

**Comment by NickM72** [comment]
I am experiencing a new variant of this, I successfully passed through the partkeepr setup steps incl. creation of the DB but now when I want to run the application I get said "An Exception was thrown while handling: Internal Server Error" message.

I am using an external SQL server, is it possible that the container does not store the credentials provided during setup but is trying to access the DB with the default settings? Inspect on the container shows e.g. "PARTKEEPR_DATABASE_HOST=database" in ENV which would be wrong if relevant.

Anyone ever connected mhubig/docker-partkeepr to an external/shared SQL server successfully?

**Comment by NickM72** [comment]
Got to work it now, I believe there was an issue with the dns resolution of the sql server, pointing to the ip directly got it running.

**Comment by mhubig** [comment]
OK good to know! Closing now, but if you need further assistance feel free to reopen ...
