### ISSUE TITLE
Authentification Key

### ISSUE THREAD

**Issue by dboeglin** [mhubig/docker-partkeepr#22]
I am unable to find the authenfication key to proceed with the installation of the app. Where is supposed to be located the authkey.php file on the server ? Thanks for your help!

**Comment by wefixit-AT** [comment]
`docker exec -ti partkeepr cat /var/www/html/app/authkey.php`

**Comment by mhubig** [comment]
Also see the `README.md` for an example on how to do this with docker compose ...
