### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by FranciumF** [mhubig/docker-partkeepr#24]
System : Synology DS1517+ (DSM 6.2)
Docker, mhubig/partkeepr

setting up the partkeepr, when testing for database connectivity, error occurs
"An exception occured in driver : SQLSTATE[HY000][2002] php_network_getaddresses: getaddrinfo failed: Name or service not known"

default values for database is used, nothing is changed.

**Comment by kkiper** [comment]
did you ever figure this out? I came across the same issue

**Comment by azzajess** [comment]
Same problem with OMV docker.
