### ISSUE TITLE
Octopart Integration not working

### ISSUE THREAD

**Issue by Chris-42** [mhubig/docker-partkeepr#32]
I installed the docker on my synology and tried to integrated octopart in the config without success.
It seems in template for mkparameters the env Variable ist wrong. Its OKTOPART instead of OCTOPART.
But anyway after adding the key manually its still not working. The call to/api/octopart is returning 500.

**Comment by TroyDowling** [comment]
I believe the K versus C change just comes from the history of the project being written by a German-speaking author. Now it has been internationalised. The bigger issue is that Octopart released a new API version 4 and seems to have killed version 3 which PartKeepr is still using. There is a [PR in the main PartKeepr project](https://github.com/partkeepr/PartKeepr/pull/1150), so hopefully this will get fixed soon.
