### ISSUE TITLE
Error after import with part edit.

### ISSUE THREAD

**Issue by boiddude** [mhubig/docker-partkeepr#33]
It looks like I might have found a bug.  I have had to rebuild my setup multiple times now due to it.  Everything is ok after I import everything (besides stock not working). 

It looks like there is an issue after importing data into partkeepr.  I followed this process. 

Using Ubuntu 20.04
1) downloaded the latest partkeepr from mhubig/docker-partkeepr.  
2) docker-compose up to get it up and running
3) Create a new project and saved it
4) imported Storage Locations after creating a new category under root category. 
5) imported parts under the import in the project I created. 
6) Everything seems to work fine but while I can remove columns from my view in Part Manager I am unable to actually enter anything into Status or Condition fields now. I get the error below. 

I need to be able to somehow create or input categories in some field that will allow me to put parts in certain priority by categories such as A, B, C, D.  I was just going to put it into Condition or Status but not happening with the error. 

An error occurred

Details
==================================
Type error: Argument 1 passed to Proxies\__CG__\PartKeepr\StorageLocationBundle\Entity\StorageLocation::setCategory() must be an instance of PartKeepr\StorageLocationBundle\Entity\StorageLocationCategory, null given, called in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php on line 591

Request
==================================
PUT /api/parts/4051?_dc=1595625348702

[object Object]

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Type error: Argument 1 passed to Proxies\\__CG__\\PartKeepr\\StorageLocationBundle\\Entity\\StorageLocation::setCategory() must be an instance of PartKeepr\\StorageLocationBundle\\Entity\\StorageLocationCategory, null given, called in \/var\/www\/html\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/PropertyAccess\/PropertyAccessor.php on line 591"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.1.33
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.WSSEAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: false
defaultGridPresets: []

**Comment by christianlupus** [comment]
As a remark, this issue is most probably not related to this docker-compose repository. There is a [duplicate issue in the partkeepr repository](https://github.com/partkeepr/PartKeepr/issues/1145) with exactly the same error message. I suggest to close this one.
