### ISSUE TITLE
Message box after login: The following cronjobs aren't running

### ISSUE THREAD

**Issue by whc2001** [mhubig/docker-partkeepr#34]
After login the webpage says:
```
The following cronjobs aren't running:

partkeepr:cron:synctips
```

The content in `/etc/cron.d/partkeepr` of main container is:
```
*/10 * * * * /usr/local/bin/php /var/www/html/app/console partkeepr:cron:run 2>&1 > /proc/1/fd/1
# Don't remove the empty line at the end of this file. It is required to run the cron job
```

Tried to run `/usr/local/bin/php /var/www/html/app/console partkeepr:cron:run 2>&1 > /proc/1/fd/1` manually, got:
```


  [Doctrine\DBAL\Exception\ConnectionException]
  An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'partkeepr'@'172.24.0.4' (using password: YES)



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'partkeepr'@'172.24.0.4' (using password: YES)



  [PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'partkeepr'@'172.24.0.4' (using password: YES)


partkeepr:cron:run [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>


```

However I can operate the software, adding components and storage locations all seem to work normally. Is there any solution for the pop-up window?

**Comment by mhubig** [comment]
This should be fixed by the cronjob section within the docker-compose file ... but I'll take another look at it.

**Comment by whc2001** [comment]
> This should be fixed by the cronjob section within the docker-compose file ... but I'll take another look at it.

I tried to run the command inside `crontab` file and got the SQL error... So not sure whether it's cron job not running or it just fails. I am not sure how to install PartKeepr manually (it's very picky about the version of LAMP stack) so I am unable to ensure whether it's PartKeepr itself or it's something inside docker.

**Comment by whc2001** [comment]
Sorry for your effort, but that's another silly user error. During installation I changed the SQL password of user `partkeepr` from the default `partkeepr` to something else, but the `$container->setParameter('database_password', ...);` line under `/var/www/html/app/config/parameters.php` did not change along for some reason. After correcting with the valid password the cron command can be executed successfully and the pop up seems to go away.
