### ISSUE TITLE
Database Connection Error

### ISSUE THREAD

**Issue by S1L3NTANG3L** [mhubig/docker-partkeepr#46]
I keep getting this error while trying to connect to the mysql docker in the database step.
An exception occured in the driver: SQLSTATE[HY000][2002] php_network_getaddresses: getaddrinfo failed: Name or service not known.
Any suggestion on how to get around this?
![Un1titled](https://user-images.githubusercontent.com/37051908/128769082-b5beeeb8-05bb-43bf-b998-34f132765ab2.png)
![Unti2tled](https://user-images.githubusercontent.com/37051908/128769086-cd75af5e-24e1-4f2d-85d5-c09c9213a9bb.png)

**Comment by meulfire** [comment]
I just ran into this issue today... I tried several things to fix it, and ultimately determined my SQL Server had crashed... I don't know how to restart the SQL Server by itself (Even MyPHPAdmin wasn't working), so I just wound up restarting my whole machine (a NAS), and that worked. 
If your question is based on problems with initial setup, then I suggest double-checking the Database Host Name (when I was setting it up, I had a typo in the name).

**Comment by S1L3NTANG3L** [comment]
I am running MySQL as a docker so it was easy to restart, I figured out dumbly the hostname needs to be the ip address of the machine hosting the sql server. The next issue came after this as soon as the database setup completes it returns an error "Invalid response from server" and I'm not sure how to fix that.
