### ISSUE TITLE
Increase PHP upload_max_filesize 

### ISSUE THREAD

**Issue by Germwalker** [mhubig/docker-partkeepr#47]
Heya, 

I would like to increase the upload_max_filesize parameter from php.ini file.

Here are the options : 
upload_max_filesize = 20M
post_max_size = 21M

I'm not a docker expert, i tried to rebuild the docker partkeepr container with the modified php.ini but it's not working as the new parameters are not updated inside the container. 

I don't want to lose my database, how can i rebuild the container with the new php.ini ?

**Comment by GH15ADF** [comment]
Here is my temporary solution. I suppose this will get undone if I redeploy the containers.

Complete php.ini file:
[PHP]
short_open_tag = Off
max_execution_time = 180
upload_max_filesize = 20M
post_max_size = 20M

[Date]
date.timezone = "America/New_York"

Assuming a clone of https://github.com/mhubig/docker-partkeepr in your $HOME and the edits as above...
Steps:
1. Stop the partskeeper Docker containers
2. SSH to server running Docker container
3. cd ~/docker-partskeeper
4. docker cp php.ini docker-partkeepr_partkeepr_1:/usr/local/etc/php/
5. Restart the Docker containers
