### ISSUE TITLE
Internal server error (fresh install)

### ISSUE THREAD

**Issue by Xanarkan** [mhubig/docker-partkeepr#48]
Hi everybody !

I just performed a fresh install with the docker-compose file, ran through the setup wizard and then when the wizard ends:
**An Exception was thrown while handling: Internal Server Error**

The only environment variable I set was the database credentials.
Is this normal ? What can I do ?

**Comment by avatar7008** [comment]
This happens when you try to access it via http://localhost:8080.

Do http://localhost:8080/setup instead

**Comment by Lungshot** [comment]
this is good to know - maybe add to readme?

**Comment by Lungshot** [comment]
maybe I should read the readme. nevermind lol.
