### ISSUE TITLE
Average price issue

### ISSUE THREAD

**Issue by grginho** [mhubig/docker-partkeepr#54]
I have the docker setup fully working. 

The only issue is the problem with the calculation of the average price.
Let's follow this scenario:
1. Add 3 pcs with the price of 10$ per item (The average price is 10$)
2. Add 2 pcs with the price of 20$ per item (The average price is 14$ which is correct because we have in total 70$/5pcs=14$/pcs) 
3. Remove 4 pcs from the stock (The average price shown on the last item is 20$ which can't be correct)
![image](https://user-images.githubusercontent.com/47352976/232622060-49ce65d4-f46c-4338-acfb-d2fc91c1d2b6.png)

I think that the average price shouldn't be changed by removing stock because it is calculated while adding parts. In the upper scenario we removed 4 pcs with the price of 4*14$=56$ and we should have one item remaining with the price of 14$ which gives us a total price of 70$. 
If the price of the last item is 20$, that will indicate that we inserted 76$ instead of 70$.

**Comment by mhubig** [comment]
Please report this upstream: https://github.com/partkeepr/PartKeepr
