### ISSUE TITLE
Testing for database connectivity fails.

### ISSUE THREAD

**Issue by DylanBartlett** [mhubig/docker-partkeepr#8]
I'm trying to deploy partkeepr through docker on Windows 10. 

After walking through the setup steps I get to the "Testing Database Connectivity" step which fails with the following error message.

![image](https://user-images.githubusercontent.com/31410384/42504604-33f3dcd6-8434-11e8-9cac-1841c041cbe8.png)

I have used the default database settings so I'm not sure why setup is failing right off the bat.

**Comment by mhubig** [comment]
Are you using ```docker-compose``` to start the container?

**Comment by vinii8817** [comment]
@mhubig 
When I tried to create in Ubuntu server, I had the same problem,
the container MariaDB did not start, I received a permission error in the /tmp folder.
The solution was simple, when I run the docker-compose as root I had problems, but after running using sudo everything worked perfectly.

I do not know if there are other ways to solve, I'm just quoting my experience to try to help in the solution.

**Comment by mhubig** [comment]
@vinii8817 good succession! I removed the local mount from the `docker-compose.yml` file.

**Comment by mhubig** [comment]
@DylanBartlett you can try to use the updated version (`docker pull mhubig/partkeepr && docker-compose up`) and see if this fixes your problem ...

**Comment by DylanBartlett** [comment]
Hi @mhubig , I must be doing something seriously wrong here. I've ran the `docker pull mhubig/partkeepr && docker-compose up ` as you've shown here but I get the following error. 

```
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

My process for this is as follows.

1. Open Docker Quickstart
2. Run the command you listed.
3. Error.

Do I need to already have a database up and running? I'm not really a docker user by any stretch so I feel like there's a unspoken step that I'm not following.

**Comment by mhubig** [comment]
HI @DylanBartlett, there is indeed an unspoken step! You first need to clone this project to have the `docker-compose.yml` file present. Here is the whole process from the scratch:
```bash
$ git clone https://github.com/mhubig/docker-partkeepr.git
$ cd docker-partkeepr
$ docker pull mhubig/partkeepr
$ docker-compose up
```
 Thanks for pointing this out, I'll update the README ...
